[package]
name = "access-point-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "*", features = ["json"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
pwhash = "*"
google_maps = "3.7.1"
